assistant-ui/assistant-ui

- packages/react/src/primitives/thread/ThreadViewport.tsx
Reset the timeout while scrolling is in progress for more reliable isScrollingToBottomRef
> fix: Refactor scrolling logic in Thread Viewport

- apps/www/pages/docs/guides/Branching.mdx
- packages/react/src/actions/useGoToNextBranch.tsx
- packages/react/src/actions/useGoToPreviousBranch.tsx
- packages/react/src/actions/useReloadMessage.tsx
- packages/react/src/adapters/vercel/VercelAIAssistantProvider.tsx
- packages/react/src/adapters/vercel/VercelRSCAssistantProvider.tsx
- packages/react/src/adapters/vercel/useDummyAIAssistantContext.tsx
- packages/react/src/adapters/vercel/useVercelAIBranches.tsx
- packages/react/src/primitives/actionBar/ActionBarRoot.tsx
- packages/react/src/primitives/branchPicker/BranchPickerCount.tsx
- packages/react/src/primitives/branchPicker/BranchPickerNumber.tsx
- packages/react/src/primitives/message/MessageIf.tsx
- packages/react/src/primitives/message/MessageProvider.tsx
- packages/react/src/primitives/thread/ThreadMessages.tsx
- packages/react/src/utils/context/stores/AssistantTypes.ts
- packages/react/src/utils/context/stores/MessageTypes.ts
- merge append and editAt functions
- add parentId to message objects
- merge useBranchObserver into useThread
- add createdAt to messages
- merge branchState into messages
> refactor: message and assistant context

- packages/react/src/actions/useReloadMessage.tsx
- packages/react/src/adapters/vercel/VercelAIAssistantProvider.tsx
- packages/react/src/adapters/vercel/VercelRSCAssistantProvider.tsx
- packages/react/src/adapters/vercel/useDummyAIAssistantContext.tsx
- packages/react/src/adapters/vercel/useVercelAIBranches.tsx
- packages/react/src/primitives/composer/ComposerInput.tsx
- packages/react/src/primitives/composer/ComposerRoot.tsx
- packages/react/src/utils/context/stores/ComposerStore.ts
> refactor: decouple scrollToBottom behavior from thread context

- examples/with-vercel-ai-rsc/app/page.tsx
- packages/react/src/adapters/vercel/VercelRSCAssistantProvider.tsx
- packages/react/src/adapters/vercel/useVercelAIThreadState.tsx
- packages/react/src/index.ts
- packages/react/src/primitives/message/MessageContent.tsx
- packages/react/src/utils/context/stores/AssistantTypes.ts
and other message type names for better clarity
> refactor: Rename CreateThreadMessage -> AppendMessage

- packages/react/src/adapters/core/local/useLocalRuntime.tsx
> fix: useInsertionEffect to set adapter in useLocalRuntime

- packages/react/src/runtime/vercel-ai/ui/use-chat/VercelAIUIRuntime.tsx
Cancellation of an optimistic message could result in a non-leaf node in the MessageRepository becoming the `head`, this edge case is now fixed
> feat: Vercel AI SDK UI cancellation / branching interop

- README.md
- packages/cli/package.json
- packages/cli/src/commands/add.ts
- pnpm-lock.yaml
> fix: use cross-spawn for Windows support

- .changeset/beige-sheep-rest.md
- apps/www/pages/reference/primitives/Thread.mdx
- packages/react/src/primitive-hooks/thread/useThreadViewportAutoScroll.tsx
- packages/react/src/primitives/thread/ThreadViewport.tsx
- packages/react/src/utils/hooks/useManagedRef.ts
- packages/react/src/utils/hooks/useOnResizeContent.tsx
and fix an edge case in isScrollingToBottom handling
> feat: Primitive Hook useThreadViewportAutoScroll

- examples/with-inline-suggestions/components/ui/assistant-ui/AI_ThreadSuggestion.tsx
- examples/with-inline-suggestions/components/ui/assistant-ui/LastMessageHook.tsx
> fix(examples/inline-messages): deduplicate requests 

- packages/react/src/styles/tailwindcss/thread.css
- packages/shadcn-registry/registry/assistant-ui/full/thread.tsx
- packages/shadcn-registry/registry/assistant-ui/thread.tsx
to allow for the addition of new buttons for audio / file upload
> refactor: composer style update

- .changeset/config.json
- .changeset/fair-jokes-leave.md
- packages/cli/src/commands/create.ts
> cli: use cross-spawn for windows compat

- apps/docs/app/docs/[[...slug]]/page.tsx
> fix(docs): 500 server error

- apps/docs/content/docs/runtimes/langgraph/index.mdx
> docs(langgraph): add instructions for connecting to production API server

- apps/docs/content/docs/runtimes/langgraph/tutorial/part-1.mdx
it currently install blank next app
> Update part-1.mdx 

- .changeset/bright-ladybugs-brake.md
- .changeset/popular-maps-rule.md
- packages/react/src/context/providers/TextContentPartProvider.tsx
> feat: TextContentPartProvider isRunning

- .changeset/fair-shrimps-raise.md
- packages/react/src/runtimes/external-store/external-message-converter.tsx
> fix: include attachments prop in the useExternalMessageConverter

- packages/react-markdown/src/tailwindcss/index.ts
- packages/react/src/tailwindcss/index.ts
fixes #933
Co-Authored-By: Travis James <travis@tribehealthsolutions.com>
> fix: tailwindcss import fix

- .changeset/silly-jeans-yell.md
- packages/react-langgraph/src/convertLangchainMessages.ts
- packages/react-langgraph/src/types.ts
> feat(langgraph): handle MessageContentComplex types

- .changeset/good-impalas-applaud.md
- packages/react-playground/src/lib/playground-runtime.ts
- packages/react/src/api/AssistantRuntime.ts
- packages/react/src/runtimes/external-store/useExternalStoreRuntime.tsx
- packages/react/src/runtimes/local/useLocalRuntime.tsx
> fix: do not export internal Runtime types

- .changeset/curvy-keys-joke.md
- packages/react-langgraph/src/convertLangchainMessages.ts
- packages/react-langgraph/src/types.ts
> fix(langgraph): allow complex content in ai messages

- .changeset/gold-spies-teach.md
- packages/react-langgraph/src/useLangGraphMessages.ts
> fix: depenency array of react-langgraph useLangGraphMessages hook

- packages/react/src/context/react/index.ts
Co-Authored-By: xiangst <280304286@163.com>
> feat: add useAttachment / useAttachmentRuntime export

- .changeset/honest-monkeys-doubt.md
- packages/react/src/runtimes/edge/streams/assistantDecoderStream.ts
- packages/react/src/runtimes/edge/streams/runResultStream.ts
Co-Authored-By: Abdulaziz Alaboudi <Alaboudi1@users.noreply.github.com>
> fix(ai-sdk): DataStream interop without tool call streaming

- apps/docs/app/(home)/page.tsx
- packages/react-ai-sdk/package.json
- packages/react-hook-form/package.json
- packages/react-langgraph/package.json
- packages/react-markdown/package.json
- packages/react-playground/package.json
- packages/react-syntax-highlighter/package.json
- packages/react-trieve/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/src/runtimes/local/LocalRuntimeCore.tsx
- packages/react/src/runtimes/local/useLocalRuntime.tsx
> fix: properly pass initialMessages to LocalRuntime

- .changeset/big-kiwis-lay.md
- .changeset/green-experts-guess.md
- packages/react-ai-sdk/package.json
- packages/react-hook-form/package.json
- packages/react-langgraph/package.json
- packages/react-markdown/package.json
- packages/react-playground/package.json
- packages/react-syntax-highlighter/package.json
- packages/react-trieve/package.json
- packages/react/package.json
- packages/tool-ui-weather/package.json
- pnpm-lock.yaml
> fix: add React 19 RC to peerDeps

- apps/docs/content/docs/ui/styled/Decomposition.mdx
- packages/react/src/ui/attachment-ui.tsx
- packages/react/src/ui/composer.tsx
- packages/react/src/ui/index.ts
- packages/react/src/ui/user-message.tsx
> docs: ComposerAttachment  -> AttachmentUI

- apps/docs/content/docs/ui/primitives/ActionBar.mdx
- apps/docs/content/docs/ui/primitives/Attachment.mdx
- apps/docs/content/docs/ui/primitives/BranchPicker.mdx
- apps/docs/content/docs/ui/primitives/Composer.mdx
- apps/docs/content/docs/ui/primitives/Message.mdx
- apps/docs/content/docs/ui/primitives/Thread.mdx
> docs: drop primtive-hooks docs

- .changeset/chilled-boats-thank.md
- packages/tsbuildutils/src/index.ts
> fix: cjs builds

- .changeset/forty-cows-attend.md
- packages/react/src/runtimes/local/LocalRuntimeCore.tsx
- packages/react/src/runtimes/local/LocalThreadListRuntimeCore.tsx
- packages/react/src/runtimes/local/useLocalRuntime.tsx
**Purpose**:
- Address a bug in the `@assistant-ui/react` package concerning thread initialization in local runtime components.
**Changes**:
- **Bug Fix**: Enhanced thread initialization by eliminating redundant data imports, refining the thread factory function, and improving reactivity in the `useEffect` hook.
- **Documentation**: Added a changeset file to record these updates.
**Impact**:
- These modifications ensure more efficient and reliable thread initialization, boosting performance in local runtime environments. 
<details><summary>Original Description</summary>
fixes #1263
</details>
> fix: thread initialization

- .changeset/giant-tools-serve.md
- packages/react-ai-sdk/package.json
- packages/react-hook-form/package.json
- packages/react-langgraph/package.json
- packages/react-markdown/package.json
- packages/react-playground/package.json
- packages/react-syntax-highlighter/package.json
- packages/react-trieve/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
Reverts assistant-ui/assistant-ui#1375
> Revert "chore: update versions"

- packages/react-ui/package.json
> chore: update react-ui to 0.1.0

- .changeset/easy-plums-shine.md
- packages/react-langgraph/src/convertLangChainMessages.ts
Added artifact support to the LangGraph integration in the React package. This enhancement allows for handling artifacts returned from LangGraph tool calls.
**New Features**
- Added support for artifacts in LangGraph tool call responses.
- Updated the message converter to properly handle the artifact property from LangGraph messages.
This PR is part of a [stack](https://docs.mrge.io/overview), managed by [mrge](https://mrge.io):
* `main` (default branch)
* [#1640: Test code for DataStream.ts (generated by Tom, AI test code agent)](https://github.com/assistant-ui/assistant-ui/pull/1640)
* **[#1802: feat(langgraph): artifact support](https://github.com/assistant-ui/assistant-ui/pull/1802)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/assistant-ui/assistant-ui/pull/1802))
---
> feat(langgraph): artifact support

- pnpm-lock.yaml
Updated the assistant-stream dependency version in the pnpm lockfile. This ensures the project uses the latest compatible version of the package.
- **Dependencies**
- Updated assistant-stream dependency from version 0.0.31 to 0.0.32.
This PR is part of a [stack](https://docs.mrge.io/overview), managed by [mrge](https://mrge.io):
* `main` (default branch)
* [#1640: Test code for DataStream.ts (generated by Tom, AI test code agent)](https://github.com/assistant-ui/assistant-ui/pull/1640)
* **[#1805: fix: lockfile update](https://github.com/assistant-ui/assistant-ui/pull/1805)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/assistant-ui/assistant-ui/pull/1805))
---
> fix: lockfile update

- .changeset/sixty-plums-tie.md
- packages/react-ai-sdk/src/ui/utils/convertMessage.ts
Co-Authored-By: songhandong <songhandong@baidu.com>
> feat: use new AI SDK UI Parts

- .changeset/new-moons-obey.md
Using packages that are not versioned
> fix: delete .changeset/new-moons-obey.md

- apps/docs/app/(home)/shadcn-ui/page.tsx
- apps/docs/content/docs/api-reference/integrations/vercel-ai-sdk.mdx
- apps/docs/content/docs/runtimes/ai-sdk/use-assistant-hook.mdx
- apps/docs/content/docs/runtimes/ai-sdk/use-chat-hook.mdx
- apps/docs/content/docs/runtimes/ai-sdk/use-chat.mdx
- apps/docs/content/docs/runtimes/langserve.mdx
- apps/docs/package.json
- examples/with-openai-assistants/app/MyRuntimeProvider.tsx
- examples/with-openai-assistants/package.json
- pnpm-lock.yaml
in assistant example and all references in docs
> fix(deps): Replace deprecated `ai/react` with `@ai-sdk/react`

- apps/docs/content/docs/ui/SyntaxHighlighting.mdx
Fixes import in bundle optimization section, reorder sections
> chore(docs): Correction to syntax highlighting doc

- apps/registry/src/registry.ts
- packages/cli/src/lib/install-ai-sdk-lib.ts
- packages/cli/src/lib/install-edge-lib.ts
> fix: npx assistant-ui init
