assistant-ui/assistant-ui

packages/react/src/primitives/thread/ThreadViewport.tsx
packages/shadcn/registry/assistant-ui/thread.tsx

Add smooth scrolling behavior when reaching the bottom of the thread viewport
to improve user experience. scrollTop is now smoothly adjusted instead of jumping.

feat: add smooth scroll to thread viewport

---

packages/react/src/primitives/composer/ComposerInput.tsx
packages/react/src/utils/context/useComposerContext.ts

This is a little hacky, but it handles edits, reloads as well as scroll to bottom button presses. In all cases, it is desired that the main composer is focused again

feat: Focus on main composer whenever scroll-to-bottom is triggered

---

packages/react/src/primitives/thread/ThreadViewport.tsx

New onScroll events cause isAtBottom to turn false while smooth scrolling is enabled. Ignore these events during the transition

fix: Keep isAtBottom true while smoothly scrolling

---

packages/shadcn/registry/assistant-ui/thread.tsx

The button should not take any space in the Viewport

fix: Update ScrollToBottom button styles

---

packages/react/src/adapters/vercel/useDummyAIAssistantContext.tsx
packages/react/src/primitives/message/MessageProvider.tsx
packages/react/src/utils/context/stores/AssistantTypes.ts
packages/react/src/utils/context/stores/ComposerStore.ts
packages/react/src/utils/context/stores/MessageTypes.ts
packages/react/src/utils/context/useComposerContext.ts

Updated the import paths in several files to import from ComposerStore instead of ComposerTypes for consistency and clarity.

refactor: Thread Context - Add ThreadComposerState/Store

---

packages/react/src/runtime/core/AssistantRuntime.tsx
packages/react/src/runtime/core/AssistantRuntimeProvider.tsx

This allows more logic to be encapsulated inside the AssistantRuntime without the need for hooks or surrounding components

feat: AssistantRuntime synchronizer

---

packages/react/src/primitives/thread/ThreadViewport.tsx

to not mess with the main page's scroll position

fix: switch from scrollIntoView to scrollTo

---

packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/primitive-hooks/thread/useThreadViewportAutoScroll.tsx

this fixes a long tail of edge-case issues where the chat would simply stop scrolling during streaming mode

feat: scrolling to bottom during streaming is now instant

---

.changeset/silly-otters-smash.md
apps/docs/content/docs/docs/runtimes/custom-rest.mdx
packages/react/src/runtimes/edge/EdgeChatAdapter.ts
packages/react/src/runtimes/local/ChatModelAdapter.tsx
packages/react/src/runtimes/local/LocalThreadRuntime.tsx

add streaming support to local runtime via async iterator
Example
```ts
import { type ChatModelAdapter } from "@assistant-ui/react";
const CustomModelAdapter: ChatModelAdapter = {
async run({ messages, signal }) {
const res = await fetch("/api/chat", {
method: "POST",
body: JSON.stringify({ messages }),
signal,
});
const reader = res.body.getReader();
const decoder = new TextDecoder();
let done = false;
let content = '';
return (async function* () {
while (!done) {
const { value, done: readerDone } = await reader.read();
done = readerDone;
if (value) {
const chunk = decoder.decode(value, { stream: true });
content += chunk;
yield {
content: [{ type: "text", text: content }],
status: { type: "running" },
};
}
}
})();
},
};
export default CustomModelAdapter;
```

feat: add streaming with `useLocalRuntime`

---

apps/docs/content/docs/runtimes/custom-rest.mdx

direct usage of chat completions API causes users to think its an OK thing to directly call openai client side, which is not a good idea

docs: update streaming example

---

apps/docs/content/docs/runtimes/langgraph/index.mdx

Fixed a typo in the LangGraph Cloud Integration Docs
index.mdx
te -> the

fix: Typo in index.mdx

---

README.md

Docs pointed to https://assistant-ui.com/docs which was just a text dump. Fixed to point to https://assistant-ui.com/docs/getting-started.

Update README.md - fixed link to docs

---

apps/docs/app/(home)/layout.tsx
apps/docs/app/(home)/page.tsx
apps/docs/app/(home)/shadcn-ui/page.tsx
apps/docs/app/docs/layout.config.tsx

- Go te getting-started on cmd + click (8bd4f1b23abfd350af24bc85ea07ebaa95223615)
---
Current behavior:
https://github.com/user-attachments/assets/210a33f9-ced7-459e-ad07-6d971ee24aaa

[2024-10-09] [B2B] [General] Go to `/docs/getting-start` when opening docs in new window (cmd + click)

---

.changeset/fluffy-birds-burn.md
packages/react/src/runtimes/edge/EdgeChatAdapter.ts
packages/react/src/runtimes/edge/EdgeRuntimeRequestOptions.ts
packages/react/src/runtimes/edge/converters/toCoreMessages.ts
packages/react/src/runtimes/local/ChatModelAdapter.tsx
packages/react/src/runtimes/local/LocalThreadRuntimeCore.tsx

Implements a method of accessing ids of existing messages and new messages from the server on the Edge Runtime. This enables the server to maintain a copy of a data structure compatible with the `.import(...)` function available on some runtimes.
This PR consists of three changes:
1. The LocalRuntime's `performRoundtrip` now supplies its chat adapter's `*run` async generator with `unstable_assistantMessageId`.
2. The Edge Runtime includes `unstable_assistantMessageId` in the body of the request it makes to the backend.
3. `useEdgeRuntime` now provides an `unstable_sendMessageIds` option. When enabled, the EdgeRuntime will not strip the `id` field from messages before sending them to the server.
Usage:
```
// within runtime provider
const runtime = useEdgeRuntime({
api: "/api/chat", …
```

feat: Edge Runtime Server Accessible Ids

---

apps/docs/content/docs/getting-started.mdx

This pull request updates the `getting-started.mdx` documentation to include the new Gemini provider. The most important changes involve adding Gemini-specific instructions and updating the provider tabs to include Gemini.
Updates to provider tabs and installation instructions:
* Added "Gemini" to the `Tabs` component in multiple locations to include it as a provider option. [[1]](diffhunk://#diff-492521b40a9713efdff7cb88aaaea294b1e5501c3c10f0141c12639bfb2e4353L65-R65) [[2]](diffhunk://#diff-492521b40a9713efdff7cb88aaaea294b1e5501c3c10f0141c12639bfb2e4353L111-R115) [[3]](diffhunk://#diff-492521b40a9713efdff7cb88aaaea294b1e5501c3c10f0141c12639bfb2e4353L216-R229)
* Added installation instructions for the Gemini provider.
Updates to API endpoint examples:
* Added an example of how to create …

docs: add Gemini to LLM options in Getting Started guide

---

apps/docs/content/docs/ui/primitives/Message.mdx

This pull request includes changes to the `apps/docs/content/docs/ui/primitives/Message.mdx` file to update component usage. The changes focus on replacing the `Message.Root` component with the `MessagePrimitive.Root` component for consistency and clarity.
Component updates:
* [`apps/docs/content/docs/ui/primitives/Message.mdx`](diffhunk://#diff-0ae1b77e502d79aac1dc194849457cf84e4307abab2b11f70f06e34aae4c3bfeL20-R20): Replaced `Message.Root` with `MessagePrimitive.Root` in the `UserMessage` component.
* [`apps/docs/content/docs/ui/primitives/Message.mdx`](diffhunk://#diff-0ae1b77e502d79aac1dc194849457cf84e4307abab2b11f70f06e34aae4c3bfeL29-R29): Replaced `Message.Root` with `MessagePrimitive.Root` in the `AssistantMessage` component.

fix: updated Message.Root to MessagePrimitive.Root

---

python/assistant-stream/src/assistant_stream/serialization/data_stream.py

**Purpose**: 
- This update resolves a SyntaxError in the `encode_chunk` method to prevent runtime errors.
**Changes**:
- **Bug Fix**: Adjusted f-string expressions in `data_stream.py` for accurate JSON data formatting.
**Impact**:
- Enhances system reliability by removing a potential runtime error source. 
<details><summary>Original Description</summary>
No existing description found
</details>

Fix SyntaxError: f-string: unmatched '{' error

---

.changeset/fair-pumas-relax.md
packages/react/src/runtimes/edge/streams/AssistantStreamChunkType.ts
packages/react/src/runtimes/edge/streams/assistantDecoderStream.ts

None
---
This update resolves a minor issue in handling AI SDK annotation packets, ensuring error-free processing by modifying `AssistantStreamChunkType.ts` and `assistantDecoderStream.ts`.

fix: do not throw on AI SDK annotation packets

---

python/assistant-stream/poetry.lock
python/assistant-stream/pyproject.toml
python/assistant-stream/src/assistant_stream/assistant_stream_chunk.py
python/assistant-stream/src/assistant_stream/create_run.py
python/assistant-stream/src/assistant_stream/modules/tool_call.py
python/assistant-stream/src/assistant_stream/serialization/data_stream.py

None
---
The update introduces a `DataChunk` class to the `assistant-stream` module, enhancing data handling capabilities. Key files like `create_run.py` and `tool_call.py` now support these data chunks with improved type definitions. Additionally, the `data_stream.py` file has been updated to encode these chunks. The project version is incremented to 0.0.7, reflecting updates to the `starlette` package.

feat: assistant-stream data chunk support

---

apps/registry/registry/components/shadcn/full/thread.tsx
apps/registry/registry/components/shadcn/markdown-text.tsx
apps/registry/registry/components/shadcn/thread.tsx

Issue: default shadcn components had `aui-` prefix so when installed these classes didn't have any corresponding styles bundled
Fix: removed: `aui-` prefixes and used plain tailwind classes

fix: update classes to use un-prefixed tailwind classes

---

apps/docs/app/(home)/MyRuntimeProvider.tsx

Implemented a dummy chat adapter for testing the website interface without backend dependencies. This replaces the API-based chat runtime with a local mock that streams responses token by token.
**New Features**
- Created a `DummyChatAdapter` class that simulates chat responses with Lorem Ipsum text.
- Added token-by-token streaming with random delays to mimic real API behavior.
- Implemented special handling for initial messages with custom intro text.
**Refactors**
- Replaced `useChatRuntime` with `useLocalRuntime` to eliminate backend API dependency.
- Removed API key configuration since it's no longer needed with local runtime.
- Updated component export to use function declaration syntax for consistency.

feat: dummy chat adapter for website

---

.changeset/curly-pens-wash.md
packages/assistant-stream/CHANGELOG.md
packages/assistant-stream/package.json
packages/assistant-stream/src/core/effects/ToolExecutionStream.ts
packages/react-ai-sdk/package.json
packages/react-hook-form/package.json
packages/react-langgraph/package.json
packages/react-markdown/package.json
packages/react-syntax-highlighter/package.json
packages/react/CHANGELOG.md
packages/react/package.json

Fixed a bug that prevented crashes when tool calls have empty argsText. This improves error handling in the assistant-stream package by gracefully handling unexpected empty arguments.
**Bug Fixes**
- Added proper error handling for tool calls with empty argsText instead of crashing
- Improved error messaging to better identify the unexpected condition
- Added logging to help diagnose when this edge case occurs
This PR is part of a [stack](https://docs.mrge.io/overview), managed by [mrge](https://mrge.io):
* `main` (default branch)
* [#1640: Test code for DataStream.ts (generated by Tom, AI test code agent)](https://github.com/assistant-ui/assistant-ui/pull/1640)
* **[#1804: fix: do not crash on tool call with empty argsText](https://github.com/assistant-ui/assistant-ui/pull/1804)** ⬅️ …

fix: do not crash on tool call with empty argsText

---

.changeset/hungry-wings-occur.md
packages/assistant-stream/src/core/ToolResponse.ts

Fixed ToolResponse instanceof check using a named symbol to prevent version mismatch issues. This approach ensures reliable type checking even when multiple versions of the package exist in the same application.
**Bug Fixes**
- Added a Symbol.for() implementation to make instanceof checks resilient against version mismatches
- Implemented Symbol.hasInstance to properly identify ToolResponse objects across different package versions
- Created a named symbol (TOOL_RESPONSE_SYMBOL) that works consistently in JavaScript's global symbol registry
To be resiient against version mismatches

fix: ToolResponse instanceof check via named symbol

---

packages/react/tsconfig.json

Addition of `rootDir` to `packages/react/tesconfig.json`
```json
"compilerOptions": {
"rootDir": "src"
},
```
This is needed to fix build errors when deploying on node22

fix(ci): Add `rootDir` to `tsconfig.json` in `@assistant-ui/react`

---

apps/docs/content/docs/migrations/meta.json
apps/docs/content/docs/migrations/v0-11.mdx

---
This PR introduces a migration guide for version 0.11 of the assistant-ui library. The primary change involves renaming 'ContentPart' to 'MessagePart' across various types, components, hooks, and contexts to improve semantic clarity and consistency. The migration guide provides detailed instructions for both automatic and manual codebase updates, ensuring a smooth transition for developers.
**Complexity**: 🟡 MEDIUM
- Renaming of ContentPart to MessagePart across types, components, and hooks
- Introduction of a migration guide for version 0.11
- Deprecation of old ContentPart APIs
*Analysis generated by [BugShoot](https://bugshoot.dev)*

docs: migration guide for v0.11

---

apps/registry/scripts/build-registry.ts

build script now deploys registry.json to https://r.assistant-ui.com/registry.json
this allows @assistant-ui to be added to the shadcn cli trusted registries, enabling namespace support out of the box:
`xpx shadcn@latest add @assistant-ui/thread` (pending merge of https://github.com/shadcn-ui/ui/pull/8312)

fix(registry-build): add registry.json to hosted registry
